#warning Never reference the Resource Staging library in your game. It's just here to generate our XNB files.

// Note: We don't need to create an Xbox 360 version of this
// project since an XNB is an XNB. We're not insterested in
// the DLL (the game library) that's generated by this project,
// we're just interested in the media that's been processed by
// the Content Pipeline. -- joe